### ISSUE TITLE
Using simmr with data.frames wrong labels in plot 

### ISSUE THREAD

**Issue by lsaravia** [andrewcparnell/simmr#1]
I am trying to use simmr with the same old siar example files

```
sources <- read.table("sourcesdemo.txt",header=TRUE,stringsAsFactors = F)
consumers <- read.table("geese1demo.txt",header=TRUE)
corr <- read.table("correctionsdemo.txt",header=TRUE,stringsAsFactors = F)

sm1 <- simmr_load(mixtures=as.matrix(consumers),
		   source_names=sources$Means,
		   source_means = sources[,c(2,4)],
		   source_sds = sources[,c(3,5)],
		   correction_means = corr[,c(2,4)],
		   correction_sds = corr[,c(3,5)]
		   )

print(sm1)

plot(sm1)
```
But the labels of the plot seems to be wrong

![image](https://cloud.githubusercontent.com/assets/1203501/9775725/da628cd0-5727-11e5-925c-4ccc9361b447.png)

you could find the text files I am using in <https://github.com/AndrewLJackson/SIAR-examples-and-queries/tree/master/siar-mixing-models>

Thanks!

**Comment by andrewcparnell** [comment]
Hi,

This occurs because the default x-axis label for iso-space plots in simmr is 'd13C' and the default y-axis is 'd15N'. See `help(plot.simmr_input)` for details. If you want to change the axis labels you can use, e.g.
```
plot(sm1, xlab='d15N', ylab='d13C')
```

I'll change this in a future version to avoid others getting confused with this.

Andrew

**Comment by andrewcparnell** [comment]
I've updated the github master version so this should no longer happen.

**Comment by lsaravia** [comment]
Thanks Andrew! you found another mistake I wasn't aware, I wasn't clear enough, I was referring to the legend labels, the first one is Enteromorpha that is a source, besides the colours are correct it puts the mixtures in the middle so it is confusing.

**Comment by andrewcparnell** [comment]
That's strange. I don't get that plot. By running this below code:

```
sources <- read.table(url("https://raw.githubusercontent.com/AndrewLJackson/SIAR-examples-and-queries/master/siar-mixing-models/sourcesdemo.txt"),header=TRUE,stringsAsFactors = F)
consumers <- read.table(url("https://raw.githubusercontent.com/AndrewLJackson/SIAR-examples-and-queries/master/siar-mixing-models/geese1demo.txt"),header=TRUE)
corr <- read.table(url("https://raw.githubusercontent.com/AndrewLJackson/SIAR-examples-and-queries/master/siar-mixing-models/correctionsdemo.txt"),header=TRUE,stringsAsFactors = F)

# Run the below to get the latest github version
#devtools::install_github('andrewcparnell/simmr')
library(simmr)
sm1 <- simmr_load(mixtures=as.matrix(consumers),
                  source_names=sources$Means,
                  source_means = sources[,c(2,4)],
                  source_sds = sources[,c(3,5)],
                  correction_means = corr[,c(2,4)],
                  correction_sds = corr[,c(3,5)])

print(sm1)

plot(sm1)
```
I get:

![pic2](https://cloud.githubusercontent.com/assets/3535973/9800537/595d0c6c-5805-11e5-8029-5440474b73f1.png)

which looks right to me.

Is there something I'm missing or has the data you've loaded in got corrupted?

Andrew

**Comment by lsaravia** [comment]
I guess you are using windows because in linux I have to use RCurl to read https data from github,  

```

library(RCurl)
x <- getURL("https://raw.githubusercontent.com/AndrewLJackson/SIAR-examples-and-queries/master/siar-mixing-models/sourcesdemo.txt")
sources <- read.table(text=x,header=TRUE,stringsAsFactors = F)
x <- getURL("https://raw.githubusercontent.com/AndrewLJackson/SIAR-examples-and-queries/master/siar-mixing-models/geese1demo.txt")
consumers <- read.table(text=x,header=TRUE)
x <- getURL("https://raw.githubusercontent.com/AndrewLJackson/SIAR-examples-and-queries/master/siar-mixing-models/correctionsdemo.txt")
corr <- read.table(text=x,header=TRUE,stringsAsFactors = F)


sm1 <- simmr_load(mixtures=as.matrix(consumers),
		   source_names=sources$Means,
		   source_means = sources[,c(2,4)],
		   source_sds = sources[,c(3,5)],
		   correction_means = corr[,c(2,4)],
		   correction_sds = corr[,c(3,5)]
		   )

print(sm1)

plot(sm1)
```
And I get the same as previous, I guess it could be a Linux related thing

![image](https://cloud.githubusercontent.com/assets/1203501/9802804/5f10301a-57f3-11e5-985f-930183810462.png)

**Comment by andrewcparnell** [comment]
How bizarre. I'm using a mac. I've also just run it on my centOS linux box and I get the same (correct) graph. 

I'm not sure what else to suggest! Could you try another computer?

Andrew

**Comment by lsaravia** [comment]
Debuggin plot.simmr_input, It seems that ubuntu doesnt take into account the leading space you add 

     Source = factor(c(x$source_names, rep(" Mixtures", nrow(curr_mix))))

     levels(Source)
     [1] "Grass"     " Mixtures" "U.lactuca" "Zostera"  

adding this 

     Source <-relevel(Source," Mixtures")
     Browse[2]> levels(Source)
     
     [1] " Mixtures" "Grass"     "U.lactuca" "Zostera"  

change " Mixtures" to the first place.

**Comment by lsaravia** [comment]
More problems adding groups:

```

sources <- read.table("sourcesdemo.txt",header=TRUE,stringsAsFactors = FALSE)
consumers <- read.table("geese2demo.txt",header=TRUE,stringsAsFactors = FALSE)
corr <- read.table("correctionsdemo.txt",header=TRUE,stringsAsFactors = FALSE)
concs <- read.table("concdepdemo.txt", header=TRUE,stringsAsFactors = FALSE)

sm2 <- simmr_load(mixtures=as.matrix(consumers[,c(3,2)]),
		   source_names=sources$Means,
		   source_means = sources[,c(4,2)],
		   source_sds = sources[,c(5,3)],
		   correction_means = corr[,c(4,2)],
		   correction_sds = corr[,c(5,3)],
		   concentration_means = concs[,c(4,2)],
           group=consumers[,1]
)

print(sm2)

plot(sm2)


Error in `[[<-.data.frame`(`*tmp*`, aes, value = c(0, 0, 0, 0, 0, 0, 0,  : 
  replacement has 12 rows, data has 5
```

I hope you can reproduce this!

**Comment by andrewcparnell** [comment]
Yes that's a great suggestion regarding the levels - I should really treat it as a factor. I'll look at the group problem shortly.

**Comment by andrewcparnell** [comment]
OK updated the master version on github to fix both of these. Let me know if they work for you.

**Comment by lsaravia** [comment]
Thanks Andrew it works ok!
