### ISSUE TITLE
Siarplotdata(...) just for one group

### ISSUE THREAD

**Issue by xiaoweige2** [andrewcparnell/simmr#10]
Thank you for your great package. However, when I just divided one group in my data frame of "consumers", the x-aixs in the plot appears "group" but not "d15N" or "d13C"in theory. The problem would disappear in  multi-group version. I also found other people faced the same issue.
https://github.com/AndrewLJackson/siar/issues/6
![rplot03](https://user-images.githubusercontent.com/32350561/31665675-3c96b4dc-b37c-11e7-993b-b07068da0692.jpeg)

**Comment by andrewcparnell** [comment]
Hi Xiaoweige2,

I think you might have put this on the wrong page. This looks to be a SIAR problem? This is the page for simmr.

Andrew
