### ISSUE TITLE
Running simmr on mean values for consumers?

### ISSUE THREAD

**Issue by Mermessus** [andrewcparnell/simmr#11]
Hi,

I am trying to use previously published dataset for a meta-analysis. Usually, only mean + sd values per sampling site are provided for consumers and sources. The CRAN page says that "simmr can handle [...] 
A single consumer. This may occur when you have only one data point on a single individual". Does this mean that you can run the model on only one observation? By extension can I run simmr on one mean value and is there a way to take into account the sd? 

Thank you very much
Best regards

**Comment by andrewcparnell** [comment]
Hi Mermessus,

Thanks for the message. Yes you can run simmr on a single observation. It's exactly the same as a normal run. Unfortunately there's no way to include the sd. You might be able to do this using MixSIAR instead though?

Andrew

**Comment by Mermessus** [comment]
Hi, 

Thank you for the answer. Unfortunately, MixSIAR doesn't seem to handle this either...

Regards

**Comment by andrewcparnell** [comment]
Hmm. That's annoying. It should just be a small-ish change to the JAGS model. Unfortunately I just don't have the time to implement it right now I'm afraid. 

How familiar are you with running and interpreting JAGS models by yourself? It might be something we could do together.

**Comment by Mermessus** [comment]
I am not familiar at all but this is something I was planning to learn. I
will have a look and tell you if I think I can help...

2017-10-23 22:27 GMT+02:00 Andrew Parnell <notifications@github.com>:

**Comment by andrewcparnell** [comment]
If you can get to the point where you can run JAGS models and interpret the output I can give you the appropriate JAGS code for the meta-analysis model you want to fit.

Perhaps the place to start would be our SIMMs course, start [here](https://rawgit.com/andrewcparnell/simms_course/master/Timetable.html).

**Comment by Mermessus** [comment]
Ok, I read all the course (which I found very good), it will be ok. Can you send me the appropriate JAGS code please?

**Comment by andrewcparnell** [comment]
OK here's my suggested code for a new simmr model:
```
model {
  # Likelihood
  for (j in 1:J) {
    for (i in 1:N) {
      y_mean[i,j] ~ dnorm(inprod(p*q[,j], s_mean[,j]+c_mean[,j]) / inprod(p,q[,j]), 1/var_y[j])
    }
    var_y[j] <- inprod(pow(p*q[,j],2),pow(s_sd[,j],2)+pow(c_sd[,j],2))/pow(inprod(p,q[,j]),2)
+ pow(sigma_obs[j],2) +  pow(sigma[j],2)
  }

  # Prior on sigma
  for(j in 1:J) { sigma[j] ~ dunif(0,sig_upp) }

  # CLR prior on p
  p[1:K] <- expf/sum(expf)
  for(k in 1:K) {
    expf[k] <- exp(f[k])
    f[k] ~ dnorm(mu_f[k],1/pow(sigma_f[k],2))
  }
}
```

The key difference is that instead of providing `y` you're providing `y_mean` and you also have to give it `sigma_obs` in the data which is the standard error for each isotope which I think you also have. 

Give that a try.

Andrew

**Comment by Mermessus** [comment]
OK, thank you. I will try it as soon as possible and let you know...

2017-10-28 18:04 GMT+02:00 Andrew Parnell <notifications@github.com>:

**Comment by Mermessus** [comment]
Hi, 

When I try to define the jags model  with siar I get an error.
Here is my code:

Definition of the dataset
```
dataAKA04Riv=list(y_mean=MixAka04RivFull[,c(1,3)],
                  s_mean=sourcesAKA04[,c(1,3)],
                  s_sd=sourcesAKA04[,c(2,4)],
                  c_mean=CorRivFull[,c(1,3)],
                  c_sd=CorRivFull[,c(2,4)],
                  sigma_obs=MixAka04RivFull[,c(2,4)],
                  N=nrow(MixAka04RivFull),K=nrow(sourcesAKA04),J=2)
```
Definition of the model
```
ModelAKA04RivFull<-jags.model(textConnection(FullModel),data=dataAKA04Riv,n.chain=3)
```
The error message:
```
RUNTIME ERROR:
Compilation error on line 19.
Unknown variable mu_f
Either supply values for this variable with the data or define it  on the left hand side of a relation.
```

I guess I should define the mu_f in the jags model like you did in your course... Something like this would be correct?
```
model {
  # Likelihood
  for (j in 1:J) {
    for (i in 1:N) {
      y_mean[i,j] ~ dnorm(inprod(p*q[,j], s_mean[,j]+c_mean[,j]) / inprod(p,q[,j]), 1/var_y[j])
    }
    var_y[j] <- inprod(pow(p*q[,j],2),pow(s_sd[,j],2)+pow(c_sd[,j],2))/pow(inprod(p,q[,j]),2)
+ pow(sigma_obs[j],2) +  pow(sigma[j],2)
  }

  # Prior on sigma
  for(j in 1:J) { sigma[j] ~ dunif(0,sig_upp) }

  # CLR prior on p
  p[1:K] <- expf/sum(expf)
  for(k in 1:K) {
    expf[k] <- exp(f[k])
    f[k] ~ dnorm(mu_f[k],1/pow(sigma_f[k],2))
  }
# Prior on mu 
for(k in 1:K) { 
    mu_f[k] ~ dnorm(0,1)
  }
}
``` 

Thank you.

**Comment by andrewcparnell** [comment]
All sounds good. Even fixing mu_f = 0 will probably work ok. I would put sigma_upp as 0.01 if N = 1, 10 otherwise is fine. You should set q = 1 to remove concentration dependence.

**Comment by Mermessus** [comment]
Hi, 

Sorry but I still get an error. I  set q=1 when defining the dataset. When I run the model I get this error:
```
Error in jags.model(textConnection(FullModel), data = dataAKA04Riv, n.chain = 3) : 
  RUNTIME ERROR:
Compilation error on line 8.
Dimension mismatch taking subset of q
```
This time I have no clue how to fix it...

Regards

**Comment by andrewcparnell** [comment]
When I said set q=1 I meant you need to set q = 1 for all the sources. q is a K by J matrix and all values need to be set to 1, e.g.
```
q = matrix(1, ncol = J, nrow = K)
```
(You'll need to put in your values of J and K).

Andrew

**Comment by Mermessus** [comment]
Ok, I run a 2 isotopes model, with 1 consumer and 2 sources. 
So N=1, K=2 and J=2. Right?

Because I get a new error:
```
RUNTIME ERROR:
Compilation error on line 6.
Dimension mismatch in subset expression of y_mean
```
Any idea?

Thanks

**Comment by andrewcparnell** [comment]
Make sure that `y_mean` is specified as a matrix when you give JAGS the data. Sometimes R automatically coerces objects into vectors (i.e. with only one dimension).

**Comment by Mermessus** [comment]
Hi, 

You were right, the previous error came from y_mean format.
Now, the error is in sigma_obs:
```
RUNTIME ERROR:
Compilation error on line 9.
Dimension mismatch taking subset of sigma_obs
```
But this time the format is ok: it is a matrix with 2 column (SDd13C and SDd15N) and 1 line. I just added a comma to get this:
```
pow(sigma_obs[,j],2)
```
Now it works! Thank you very much...

One last very useful thing would be to be able to compute the models for each consumer mean and sd values of the same data set. With simmr, I do it defining a grouping variable in which each line is a different group. Like this, simmr computes each 'solo run' in the same run. 
Do you think it is possible? Thank you.

**Comment by andrewcparnell** [comment]
Great that it's working.

All simmr is doing with the multiple groups runs is creating a `for` loop that creates the data set for JAGS using the current data and then runs the model. After the for loop it combines everything so that it can be compared (e.g. between groups).
