### ISSUE TITLE
Accessing Raw Output Data in SIMMR

### ISSUE THREAD

**Issue by cmhalffman** [andrewcparnell/simmr#12]
Can I access the raw output data in SIMMR (simmr_out)? There were instructions in the SIAR "Ecologist's Guide" section 4.3.5 for accessing the raw data (e.g., to compute an additional summary stat). I tried the same script in SIMMR:
out<-simmr_out$output
and tried to view the data using: 
fix(out)
This did open a text editor with many values separated by commas, but they are not in any sort of column format (as described in the SIAR manual), so I'm not sure what the data represent.  By the way, I have 6 sources for one individual.
Thanks!

**Comment by andrewcparnell** [comment]
Hi cmhalffman,

Yes you can! See the simmr vignette at: https://cran.r-project.org/web/packages/simmr/vignettes/simmr.html

It's in the section called 'Other advanced use of simmr'.

To explore what's fully there try:
```
str(simmr_out)
```
