### ISSUE TITLE
## sd_d13C ?

### ISSUE THREAD

**Issue by melizaantunes** [andrewcparnell/simmr#16]
Hi, Andrew.

First of all, I want to thank you for this package, it's amazing!
I'm working with it and a question arose: when I run the model, exploring the results I found ## sd_d15N and ## sd_d13C
What do they mean? Because the standard deviation of the sources has already been given
I apologize if the questioning is basic, is that it really is disturbing me a little

Thank you in advance for the help

Maria

**Comment by andrewcparnell** [comment]
Hi.

Apologies for not getting to this sooner - it didn't appear in my open issues page.

sd_d13C and sd_d15N are estimates of the residual uncertainty in the isotope values for your organisms.

Andrew
