### ISSUE TITLE
Plot quantiles

### ISSUE THREAD

**Issue by mcaputo3** [andrewcparnell/simmr#18]
Good morning!

Is there a way to plot the quantiles using simmr code ...I can extract the results from the summary function and make a ggplot version but wondering if there's a simpler way ? It would be nice to have boxplots but with quantiles for manuscripts for each prey type. Rather then the simmr output plots  

Thanks!

**Comment by andrewcparnell** [comment]
Hi mcaputo3,

simmr already produces boxplots of e.g. dietary proportions across sources or groups - see the [vignette](http://andrewcparnell.github.io/simmr/articles/simmr.html). These all are based on quantiles. Did you want a different type of boxplot? If so can you provide some e.g. ggplot code so I can see what you require?

Thanks,

Andrew

**Comment by mcaputo3** [comment]
Hi Andrew,

I’m looking for something like the attached which was included in the SIAR package. I have produced the box plots in the simmr vignettes but my colleague prefers the SIAR ones. Sorry if this is a silly question, I haven’t been able to figure out how to create these types of plots otherwise… 

Cheers
Michelle

**Comment by andrewcparnell** [comment]
Do you mean something like the bottom right of page 1 of [this](https://maths.ucd.ie/~parnell_a/media/SIAR_For_Ecologists.pdf)?

**Comment by mcaputo3** [comment]
Exactly!

I know your webpage says that the mixing model components of SIAR are being phased out  but I can always run the old code to get this plot if that’s the easiest way. 

Cheers
Michelle

**Comment by andrewcparnell** [comment]
I don't know of any way of creating those kinds of boxplots with ggplot2 which is now the basis of all the plotting functions. If you have some code or know of a ggplot extension package to do this I'm happy to put it into simmr.

Andrew

**Comment by mcaputo3** [comment]
Ok - Thanks so much for your help. I haven’t been able to figure out how to do this in ggplot but if I do I’ll be sure to share. 

Cheers
Michelle
