### ISSUE TITLE
plot_viz() error in vignette

### ISSUE THREAD

**Issue by hanvanzan** [andrewcparnell/simmr#19]
I was running through the examples in the simmr vignette (https://cran.r-project.org/web/packages/simmr/vignettes/simmr.html).  On step 6,  I get the following error:

prior_viz(simmr_out)
Error: Column `~Source` must be a 1d atomic vector or a list

**Comment by andrewcparnell** [comment]
Thanks for the feedback. Would it be possible for you to provide a reproducible example? I can't seem to re-create that error.

Andrew
