### ISSUE TITLE
Trying to use coda, is $output an mcmc.list object?

### ISSUE THREAD

**Issue by lsaravia** [andrewcparnell/simmr#2]
I am not an expert using coda but I would like to view a traceplot so I tried this

```
sources <- read.table("sourcesdemo.txt",header=TRUE,stringsAsFactors = F)
consumers <- read.table("geese1demo.txt",header=TRUE)
corr <- read.table("correctionsdemo.txt",header=TRUE,stringsAsFactors = F)

sm1 <- simmr_load(mixtures=as.matrix(consumers),
		   source_names=sources$Means,
		   source_means = sources[,c(2,4)],
		   source_sds = sources[,c(3,5)],
		   correction_means = corr[,c(2,4)],
		   correction_sds = corr[,c(3,5)]
		   )

sm1_out = simmr_mcmc(sm1)

require(coda)

traceplot(sm1_out$output)

is.mcmc.list(sm1_out$output)

```

it seems that sm1_out$output is not an mcmc.list object

thanks!

**Comment by andrewcparnell** [comment]
Try instead 

```
traceplot(sm1_out$output[[1]])
```

**Comment by lsaravia** [comment]
Thanks! So I tried

    traceplot(sm1_out$output[[1]][,1])
 
and I get the trace for the first parameter, and so on, could you tell me how I get the names of the parameters?

**Comment by andrewcparnell** [comment]
If you type:
```
str(sm1_out)
```
you'll see exactly what's in the object. To get the parameter names use, e.g.:

```
colnames(as.matrix(sm1_out$output[[1]]))
```

There might be a neater way of doing this.

**Comment by lsaravia** [comment]
Thanks! I don't figure out recursive lists yet...
