### ISSUE TITLE
Help pages: geese_data and geese_data_day_1

### ISSUE THREAD

**Issue by hanvanzan** [andrewcparnell/simmr#20]
The descriptions of the geese_data() and geese_data_day_1() functions state:
"A real Geese data set with 251 observations on 2 isotopes, with 4 sources, and with corrections/trophic enrichment factors (TEFs or TDFs), and concentration dependence means. Taken from Inger et al (2016). See link for paper"

"A real Geese data set with 9 observations on 2 isotopes, with 4 sources, and with corrections/trophic enrichment factors (TEFs or TDFs), and concentration dependence means. Taken from Inger et al (2016). See link for paper"

However, the paper appears to be from 2006, not 2016 unless I am mistaken?

**Comment by andrewcparnell** [comment]
You are most correct - thank you for spotting this. Will be fixed in the next version.
