### ISSUE TITLE
Unable to produce matrix plots by group after combining sources a posteriori

### ISSUE THREAD

**Issue by loicnmichel** [andrewcparnell/simmr#21]
Hi Andrew,

I'm currently working on a project where I'd like to combine sources a posteriori. I'm working with a fairly large number of groups (around 20).

After using combine_sources(), I noticed that while compare_groups() behaved exactly like I was expecting it to, compare_sources() and plot() seem to ignore the group argument: no matter which group I specify, I get the same plots and results every time. 

I tried that on multiple example datasets with 1, 2 or 3 tracers, the issue occurred in each of them.

What's bugging me is that I cannot produce matrix plots which I use a lot as diagnostic tools. Any idea what's happening here?

Thanks in advance

Loïc

**Comment by andrewcparnell** [comment]
Hi Loïc,

Thanks for spotting this. I don't think it was a bug with combine sources specifically, but in general it was ignoring the group output in some of the summaries more generally. If you find that the latest version hasn't fixed this problem please post again here with a reproducible example. 

Andrew

**Comment by loicnmichel** [comment]
Hi Andrew,

Thanks for your work on this package and for looking into this issue!

I'm afraid the problem persists using either the latest version from CRAN (0.4.2) or from Github (0.4.2.9000). I'm running R 4.0.1. Below is a (hopefully) reproducible example, and I'm attaching the code and data files to this message as well.

Thanks in advance...

`#Install the package either from CRAN

[simmr_combine_issue.zip](https://github.com/andrewcparnell/simmr/files/4771064/simmr_combine_issue.zip)
install.packages('simmr', dependencies = TRUE)

#Or the development version from Github
if(!require(remotes)) install.packages('remotes')
remotes::install_github('andrewcparnell/simmr')

library(simmr)
sessionInfo()

#Read in and load the data
consumers <- read.csv("Consumers.csv",header=TRUE)
sources <- read.csv("Sources.csv", header=TRUE)
TEFs <- read.csv("TEFs.csv",header=TRUE)
simmr_input = simmr_load(mixtures=as.matrix(consumers[,6:7]),
                         group=as.character(consumers$Group),
                        source_names=as.character(sources$Source),
                        source_means=cbind(sources$Meand13C,sources$Meand15N),
                        source_sds=cbind(sources$SDd13C, sources$SDd15N),
                        correction_means=cbind(TEFs$Meand13C,TEFs$Meand15N),
                        correction_sds=cbind(TEFs$SDd13C,TEFs$SDd15N),
                        concentration_means = NULL)

#Run the model
simmr_output = simmr_mcmc(simmr_input,  mcmc_control = list(iter = 100000, burn = 10000, thin = 100, n.chain = 4))

#Quickly check that model output is handled correctly at this stage
plot(simmr_output,type='matrix', group=6, title="Group 6")
plot(simmr_output,type='matrix', group=12, title = "Group 12")

compare_groups(simmr_output, groups=c(6,12), source="Sympagic")

compare_sources(simmr_output, source_names=c("Sympagic", "Himantothallus"), group=6)
compare_sources(simmr_output, source_names=c("Sympagic", "Himantothallus"), group=12)

#Everything looks fine - output looks as expected, i.e. different from one group to another, using all three functions.

#Now if we combine two of the sources
simmr_output_combine = combine_sources(simmr_output,
                                       to_combine=c('Himantothallus','Biofilm'),
                                       new_source_name='Benthic')

#Then compare_groups() will work just fine
compare_groups(simmr_output_combine, groups=c(6,12), source="Sympagic")

#But plot() or compare_sources() will just ignore the group argument and always produce the same output no matter what
plot(simmr_output_combine,type='matrix', group=6, title="Group 6")
plot(simmr_output_combine,type='matrix', group=12, title = "Group 12")

compare_sources(simmr_output_combine, source_names=c("Sympagic", "Benthic"), group=6)
compare_sources(simmr_output_combine, source_names=c("Sympagic", "Benthic"), group=12)
`

**Comment by loicnmichel** [comment]
All is fine indeed, using version 0.4.3 from GitHub. Thanks a lot!

**Comment by MollyHMoore** [comment]
Apologies if this is a silly question, but I am having this same exact problem (after "combine_sources" the "plot" function only returns the same group even if another is specified). I am using version 0.4.2 of simmr. How do I update to version 0.4.3 referenced above? I don't see it in the versions list on GitHub, and R seems to think simmr is fully updated. Or was 0.4.2 updated to include this correction? If so, somehow the issue is persisting for me. 
Thanks for your time!
-Molly

**Comment by andrewcparnell** [comment]
Hi Molly. 

Try running:
```
install.packages('simmr')
```
at your R console. This should get you the latest version. Let me know if it works (or not).

Andrew

**Comment by MollyHMoore** [comment]
Hi Andrew,

Thanks for responding! I just tried your suggestion, and the package version is still 0.4.2 and the same issue occurs. I think 0.4.2 the most updated version, correct? Sorry if I'm missing something obvious. This is the code I just ran:

`install.packages('simmr')
library(simmr)

mix.mod = matrix(c(-21.71001141,-19.64588417,-20.9574656,-17.06714211,-19.25518703,-19.35851445,
                   -21.72192097,-18.67746721,-20.39690511,-19.32397658,-18.99432685,-18.55061011,
                   -17.73634987,-16.39457342,-20.32678316,-16.71513814,-19.8841616,-19.38916787,
                   -19.37832111,-19.37819214,-18.12995887,-19.94644897,-20.23601096,-20.63793888,
                   -21.67133,-19.46719341,-19.3291061,-21.38234615,-17.85336029,-17.27511557,-20.19617394,
                   -18.22506941,-19.49515184,-17.52977401,-19.42761871,-20.09061135,-20.23850706,
                   -20.27269466,-20.97997066,-15.86992791,-17.10924601,-17.17179272,-17.0270033,
                   -19.34954856,-16.45670374,-15.74437733,-16.04418341,-15.21873793,-16.54974223,
                   -16.3845116,-16.18956755,-16.06891737,-16.53573678,-16.67032949,
                   -15.87,-21.14194216,-19.33426585,-16.88848293,-20.86229593,-15.23783151,-17.33273166,
                   -15.36213578,-15.59923355,-16.40018932,-15.34787002,-17.22684545,-17.12327528,
                   -20.04429894,-19.07437653,-16.82355222,-17.07339263,-19.62323184,-19.93296616,
                   -16.81564064,-20.73847084,-21.35803781,-18.26134465,-17.96150175,-15.9997888,
                   -22.18576727,-19.21427642,-19.4722482,-17.89304004,-18.99084987,-19.83884944, 
                   10.59238896,9.905433128,6.789436248,8.249463021,10.58948065,8.160195299,11.20100151,
                   10.53311048,12.22352486,9.033163116,10.89423735,7.318475983,9.60324306,7.890694219,
                   12.26607535,11.80021097,13.44910667,12.24546293,9.075500982,8.640928439,8.628394945,
                   8.901955229,8.70542028,8.312646335,9.992169707,9.22240334,9.845158484,9.588789973,
                   10.42598681,7.482037496,11.07951657,7.173424911,9.586548542,8.632474674,10.35529497,
                   10.16219315,12.5312471,10.81257907,10.18343397,7.774378156,8.616251529,8.324090202,
                   8.745179887,12.91764887,7.399395205,7.847865866,7.655692178,8.883660147,7.734245041,
                   7.81887773,7.936956221,7.175224281,7.992691881,7.212891335,7.837339929,
                   8.664285769,8.875249811,8.241097443,9.600531665,7.632551927,10.81787172,7.640626682,
                   8.009669468,7.803978335,8.30942622,8.689051235,9.641956717,9.82175086,10.09093422,
                   8.984900798,9.498466841,10.46248187,9.812383428,7.722830984,9.341623607,9.936309509,
                   9.829176062,9.882746824,6.800009521,9.209370561,12.2990341,9.483260281,8.821195354,
                   10.31175408,8.464635982), ncol = 2, nrow = 85)
colnames(mix.mod) = c('d13C','d15N')
s_names.mod = c("C3fruits", "Humanfoods", "Crabs", "Seabird_eggs", "Coleoptera", "Mice")
s_means.mod = matrix(c(-29.3, -16.76, -15.6, -20.2, -22.6, -23.9, -2, 5.9, 14.2, 15, 5.8, 0.4), ncol = 2, nrow = 6)
s_sds.mod = matrix(c(1.8, 0.41, 0.2, 1.3, 3.9, 1.1, 1.4, 0.07, 0.2, 1.1, 2.2, 1.5), ncol = 2, nrow = 6)
c_means.mod = matrix(c(1.6, 1.6, 1.6, 1.6, 1.6, 1.6, 2.59, 2.59, 2.59, 2.59, 2.59, 2.59), ncol = 2, nrow = 6)
c_sds.mod = matrix(c(0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.41, 0.41, 0.41, 0.41, 0.41, 0.41), ncol = 2, nrow = 6)
species.mod = c(1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,2,2,2,
                2,2,2,2,2,2,2,2,2,2,2,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3)

simmr_in.mod = simmr_load(mixtures = mix.mod,
                          source_names = s_names.mod,
                          source_means = s_means.mod,
                          source_sds = s_sds.mod,
                          correction_means = c_means.mod,
                          correction_sds = c_sds.mod,
                          group = as.factor(species.mod))

plot(simmr_in.mod,
     group = 1:3,
     xlab = expression(paste(delta^13, "C (\u2030)",
                             sep = "")), 
     ylab = expression(paste(delta^15, "N (\u2030)",
                             sep = "")), 
     title = 'Isospace plot of Modern Values',
     mix_name = 'Species')

simmr_out.mod = simmr_mcmc(simmr_in.mod)

#combine sources 
simmr_out.mod_comb = combine_sources(simmr_out.mod,
                                        to_combine = c('Crabs',
                                                       'Seabird_eggs'),
                                        new_source_name = 'Marine')

#then I try to create boxplots for each of the three groups and get the same boxplot (for species 1) each time
plot(simmr_out.mod_comb,
     type = 'boxplot',
     group = 1,
     title = 'simmr output modern opossums')
plot(simmr_out.mod_comb,
     type = 'boxplot',
     group = 2,
     title = 'simmr output modern raccoons')
plot(simmr_out.mod_comb,
     type = 'boxplot',
     group = 3,
     title = 'simmr output modern striped skunks')
`

If anything jumps out at you that I might be doing wrong, or other ideas for checking if the version is correctly updated, let me know! Thanks for your time!
-Molly

**Comment by andrewcparnell** [comment]
Hi Molly,

You're right. I was sure I sent version 0.4.3 to CRAN but obviously not. Instead you can install the GitHub version with:
```
if(!require(remotes)) install.packages('remotes')
remotes::install_github('andrewcparnell/simmr')
```
I haven't run your code above but try again after installing the new package and see if that fixed the problem.

Andrew
