### ISSUE TITLE
Issue with "combine_sources" function

### ISSUE THREAD

**Issue by annagschmidt** [andrewcparnell/simmr#24]
Hello, I am having trouble with the "combine_sources" function in simmr. 

Below is my code for getting up to this point with the example geese data included in simmr: 

# Load example data into R
path = system.file("extdata", "geese_data.xls", package = "simmr")
geese_data = lapply(excel_sheets(path), read_excel, path = path)

# Separate the data into parts
targets = geese_data[[1]]
sources = geese_data[[2]]
TEFs = geese_data[[3]]
concdep = geese_data[[4]]

# Load the data into simmr
geese_simmr = simmr_load(mixtures = as.matrix(targets[, 1:2]),
                         source_names = sources$Sources,
                         source_means = sources[,2:3],
                         source_sds = sources[,4:5],
                         correction_means = TEFs[,2:3],
                         correction_sds = TEFs[,4:5],
                         concentration_means = concdep[,2:3],
                         group = as.factor(paste('Day', targets$Time)))

# Plot the data in isospace
plot(geese_simmr, group = 1:8)

# Run through simmr
geese_simmr_out = simmr_mcmc(geese_simmr)

# Combine sources
simmr_out_combine = combine_sources(geese_simmr_out,
                                    to_combine = c('U.lactuca',
                                                   'Enteromorpha'),
                                    new_source_name = 'U.lac+Ent')

When trying to run this combine_sources step, the following error message appears: 

Error: Assigned data `apply(old_source_means[to_combine_cols, , drop = FALSE], 2, "mean")` must be compatible with row subscript `to_combine_cols[1]`.
x 1 row must be assigned.
x Assigned data has 2 rows.
ℹ Row updates require a list value. Do you need `list()` or `as.list()`?

Thank you for your assistance!

**Comment by andrewcparnell** [comment]
Many thanks for spotting this. It looks like there's been an update to tibbles that now won't accept something that worked before. It's halfway down this blogpost https://www.tidyverse.org/blog/2020/04/tibble-3-0-0/. 

 I'm updating the GitHub version shortly to fix this problem now. You can install the GitHub version with:
```
if(!require(remotes)) install.packages('remotes')
remotes::install_github('andrewcparnell/simmr')
```
See if that fixes your issue.

Andrew

**Comment by annagschmidt** [comment]
Hi Andrew, 

Yes that was able to fix my issue. Thank you very much!

Anna
