### ISSUE TITLE
Return plot output of compare_groups

### ISSUE THREAD

**Issue by johnrharley** [andrewcparnell/simmr#26]
It would be nice to be able to easily access the results of the plot=TRUE from `compare_groups()`, unless I'm missing something at the moment there's no way to make changes to the resulting ggplot object since it is printed.

I added `return(p)` to the Return output section of the function and it does what I needed, allowing me to pass subsequent `ggplot` arguments to the output e.g.

`compare_groups(simmr_groups_out,
               source_name = "Zostera",
               groups = 1:2, plot=TRUE) +
  labs(x="New Label")`

**Comment by andrewcparnell** [comment]
Yes that's a good suggestion. I'll add this as a feature to the next version.

**Comment by andrewcparnell** [comment]
Now implemented in latest GitHub version 0.4.3.9000. You can now do things like:
```
p = compare_groups(simmr_out)
p$plot + ylim(-1,1)
```
Hope that helps!

Andrew

**Comment by andrewcparnell** [comment]
Oh, and the same type of syntax works for `compare_sources` too. Thanks for the suggestion
