### ISSUE TITLE
incompatibility issue with simmr crashes RStudio in R-4.1.0

### ISSUE THREAD

**Issue by rjwest000** [andrewcparnell/simmr#27]
Using library simmr with R-4.1.0 crashes RStudio when attempting plot statements (on Linux). Seems to be an issue with one of the dependencies (JAGS, coda or both?). Working solution is to use earlier version of R (in RStudio), or to run R-4.1.0 in terminal mode.

**Comment by andrewcparnell** [comment]
Hi. Apologies for the delay - didn't spot this issue. Can you provide more details, e.g. the error message and output of `sessionInfo()`?

**Comment by rjwest000** [comment]
Hi. There are now several reports of a bug related to ggplot2, R-4.1 and
RStudio.
A fix appears to be on the way, so should get resolved without action. See:
e.g., See: https://github.com/rstudio/rstudio/issues/9373

**Comment by andrewcparnell** [comment]
OK - I won't do anything then. It looks like downgrading R solves the problem for now.
