### ISSUE TITLE
error code error in data frame yet everything appears correct? 

### ISSUE THREAD

**Issue by SharonEv** [andrewcparnell/simmr#3]
Hi,

    I successfully used Simmr for an individual consumer but when I tried to do it for the  4 consumers altogether I kept getting the error below. I have triple, quadruple checked everything (so hopefully I have found all the obvious errors!)  - and when I searched for errors fix,  it lead to bugs in being in  ggplot. So I am wondering if this is a bug?

This comes up after this code: 

simmr_groups = simmr_load(mixtures=mix,
                      source_names=s_names,
                      source_means=s_means,
                      source_sds=s_sds,
                      group=grp) 

Error in `[[<-.data.frame`(`*tmp*`, aes, value = c(0, 0, 0, 0, 1, 1, 1,  : 
  replacement has 10 rows, data has 7
Thanks for your help!

**Comment by andrewcparnell** [comment]
Hi SharonEv,

Thanks for the message. Have you tried running the simmr_load commands for multiple groups provided in the vignette? That includes some data so you can check whether yours matches the example code. 

Andrew

**Comment by SharonEv** [comment]
Yes it did run and I'm embarrassed to say in the actual plot function I had added an s (simmr_groups, group=1:4 ) to  the second group! As the error said data frame I kept getting checking through the data!  Thanks Andrew 

I have also come across something strange, I am getting the same plot for 4 of my consumers here are 2 of my lines, maybe you'll notice an error I have missed! Of course I can just run this with one consumer at a time to overcome but I thought it was a little strange. 

plot(simmr_groups_out,type=c('density','matrix'),grp=1,title='C. leucas')
plot(simmr_groups_out,type=c('density','matrix'),grp=2,title='G. garricki')

Also I was getting an error about the graphics and colour palette that would occur after a few graphs had been produced (in the work flow on the vignette it was after the density graphs) to fix it I had to do dev.off. It seems intermittent through. 

However the graphs look great! It is a really cool package - thanks!

**Comment by andrewcparnell** [comment]
To be clear - you're getting same plot (with the same title?) despite specifying a different group? If so, would it be possible for you to provide a reproducible example using, e.g. the data from the vignette? There's a section in there which produces different plots for different groups and seems to work ok.

It's hard to see where the bug is without the data.

**Comment by SharonEv** [comment]
Sorry for the delay in getting back to you! I just ran the geese data and had the same issue. So i get the same graphs, different tittles. I have attached the images so that you can see. This is the same error that I am getting my data. Here is what I used straight from your vignette.

 plot(simmr_groups_out,type=c('density','matrix'),grp=6,title='simmr output group 6')
 plot(simmr_groups_out,type=c('density','matrix'),grp=3,title='simmer output group 3')

![geese 6](https://cloud.githubusercontent.com/assets/15795275/11209827/46383828-8d6b-11e5-93b1-aa30ccfb3a7a.jpeg)
![geese 3](https://cloud.githubusercontent.com/assets/15795275/11209828/46a4cb32-8d6b-11e5-9ff2-cc381b09667c.jpeg)
[Rplot01.pdf](https://github.com/andrewcparnell/simmr/files/36573/Rplot01.pdf)
[Rplot03.pdf](https://github.com/andrewcparnell/simmr/files/36574/Rplot03.pdf)

Hope you can work out whats going on! 

thanks 
Sharon

**Comment by andrewcparnell** [comment]
Hi Sharon,

The command should be 'group' not 'grp'. I'll check to see if there's a spelling mistake in the vignette.

Andrew
