### ISSUE TITLE
Output table

### ISSUE THREAD

**Issue by DrMermaid** [andrewcparnell/simmr#30]
Hi,

I'm new to using SIMMR - I was wondering if there is a way to create an output table with the diet proportions of the used sources per individual target?

Thank you :)

**Comment by emmagovan** [comment]
Hi,
When you say individual target do you mean for each individual in the mixture? If so then this isn't something simmr can do right now, it just gives the dietary proportions for the total population. If you are looking for proportions for each individual then currently I would recommend that you have a look at MixSIAR. Hope this helps!
