### ISSUE TITLE
Understanding posterior predictive results

### ISSUE THREAD

**Issue by FlorianFerchiche** [andrewcparnell/simmr#32]
Dear Andrew,

We are currently working on a 2 sources simmr model: the mix is river particulate organic matter (we have a few different models corresponding to different sampling dates) and we have terrestrial material and phytoplankton as sources. So far the models run well and we have no major issues but interpreting the posterior predictive outputs $prop_outside and its plot from the posterior_predictive() function.

As expected, we obtain results that are either 0, 0.5 or 1. From what we understand, if 0 it means the data point (y) broadly lie in the fitted value intervals (Yrep), if 0.5 then only one data point is out, if 1, then both datapoints are outside the fitted value interval.

 

We are not sure we understood what is the fitted value interval and if we can consider our models as good or not regarding our results. Could you give us some lights about it (or some papers to read)?

 

So far, what we concluded about our model results are:

When checking the isospace plots, we understand that when we get a 0 it means the mix lie within the 'line' (between the 2 sources, no real 'polygon') and when we got 0.5 or 1 we find the mix to lie outside the 'line' between our two sources (often included in the standard deviation of one source but not the other). So the 'problem' might come from our input data.

1M$ question .... what is a polygon when we only have 2 sources? Does it include as well the standard deviation bars, instead of just being a simple 'line'?  so can we consider that even if our mix is within only one standard deviation, the model outputs are alright?

To our opinion these models (giving 0.5 or 1 as posterior predictive outputs) are not especially bad ones, because model chain convergence diagnostics (Gelman) are good and the posteriors plots look all right (distribution is not to wide, there is only one peak and it is quite narrow most of the time).

Would you agree to consider these results ok to be interpreted?

 

Thank you in advance for your help.

Kind regards,

 

Florian

**Comment by CamillaLienart** [comment]
Hi Florian, 
I also face the same problem... I am wondering if this comes from the number of tracters I used (n=2) and sources (n=2)... or maybe I am just missing some basic statistical knowledge ? :) 
Same questions ! Let me  know if you find some answers.
Maybe @andrewcparnell has some kind of answer ? 
Cheers
Camilla

**Comment by emmagovan** [comment]
Hi @FlorianFerchiche and @CamillaLienart, 
The interval generated by the posterior_predictive function comes from the posterior predictive distribution of the observations, so we would expect for a well fitting model that if we run the code
`posterior_predictive(simmr_out, prop = 0.5)`
that 50% of our predictions will lie inside the 50% posterior predictive distribution. 
When looking at the isospace plots, yes I would consider the error bars when imagining the mixing polygon. 
I hope this answers your questions! Any other problems please just let me know!

**Comment by CamillaLienart** [comment]
Thank you @emmagovan for your answer, now it makes sense to me. 
Maybe one of the problem in my models comes form the two sources only used to calculate isotope composition.
I'll manage ;) 
Kind regards
Camilla
