### ISSUE TITLE
Combining sources a posteriori

### ISSUE THREAD

**Issue by akbreezo** [andrewcparnell/simmr#4]
Andrew Jackson had written some code to combine source output as posteriori in SIAR. Is there a way to do this with SIMMR output?

**Comment by andrewcparnell** [comment]
There's no easy way to do this yet, other than by fiddling with the simmr objects which requires quite a bit of knowledge about their structure. However, I'm likely to have a chance to look at this next week (I'm teaching a [SIAR course](https://rawgit.com/andrewcparnell/simms_course/master/Timetable.html)!) so will try and create a `combine_sources` function. I'll leave this open and let you know when it's done.

Andrew

**Comment by akbreezo** [comment]
Great news! Thanks for the reply and I will wait to hear back. Good luck on the course...wish I was taking it myself.

**Comment by andrewcparnell** [comment]
The function `combine_sources` is now part of simmr! If you install the github version of simmr with:
```
library(devtools)
install_github('andrewcparnell/simmr',build_vignettes=TRUE)
library(simmr)
vignette(simmr)
```
... you'll see there's now a section illustrating the use of combine_sources on single and multi-group data. 

Obviously this is new so let me know if you find any bugs.

**Comment by akbreezo** [comment]
There seems to be an error in loading from Github now. 
![screen shot 2016-01-15 at 3 33 15 pm](https://cloud.githubusercontent.com/assets/11395859/12368960/66d23f6a-bb9d-11e5-9cea-a34e277d9af9.png)

**Comment by andrewcparnell** [comment]
That's strange. Works for me. Can you try again. I did make some changes to the vignette.

**Comment by akbreezo** [comment]
The package is loading now, but the vignette is not available. 
Error in vignette(simmr) : object 'simmr' not found

**Comment by andrewcparnell** [comment]
Apologies - there was a mistake in my command above - it should be `vignette('simmr')`. I've also rolled back a change which might have broken the vignette. Let me know if it works for you now.

**Comment by akbreezo** [comment]
Bummer...I'm still getting the same error. 
Warning message:
vignette ‘simmr’ not found

**Comment by andrewcparnell** [comment]
That is really odd. However, there is a workaround - leave out the `build_vignettes` bit of the install command. You can always read the vignette [here](https://github.com/andrewcparnell/simmr/blob/master/vignettes/simmr.Rmd) (though it's without the pretty graphs).

**Comment by andrewcparnell** [comment]
I've also just posted this update to CRAN so you'll be able to get this version through the standard `install.packages('simmr')` command shortly (assuming it passes).

**Comment by andrewcparnell** [comment]
It's now passed so the standard `install.packages` command should do the job. The vignette will come automatically with it.

**Comment by akbreezo** [comment]
Thanks so much for all of this Andrew!
