### ISSUE TITLE
Combining sources question

### ISSUE THREAD

**Issue by Wang-Chao-fan** [andrewcparnell/simmr#52]
The example from the simmr vignette shows combining sources "Grass" and "Enteromorpha" but uses the new name "U.lac+Ent," which appears incorrect. The section explains that sources with overlapping isotopic signatures are merged to simplify the model. However, if the isotopic matrix shows strong correlation between "Grass" and "Enteromorpha," the name should likely reflect this merge (e.g., "Gra+Ent"). It seems like a typo or mismatch in naming in the example. The correct name should represent the combined sources accurately？
![截屏2024-09-19 12 05 24](https://github.com/user-attachments/assets/8378fd36-de2c-425f-8953-6f6bda5f14f4)

**Comment by emmagovan** [comment]
Hi, thank you so much for this! Will fix in next update.
