### ISSUE TITLE
Can I combine more than 2 pairs of sources?

### ISSUE THREAD

**Issue by kabrantes** [andrewcparnell/simmr#6]
Hi Andrew,

I was wondering if it is possible to (a-posteriori) combine more than 1 pair of sources in simmr, e.g. to combine 2 sources into 1, and two other sources into another one? If so, how can i go about it?
Cheers!!

**Comment by andrewcparnell** [comment]
Hi Kabrantes,

Yes this is perfectly possible. You just need to run the `combine_sources` command as many times as the sources you want to combine. If you look at the [vignette](https://cran.r-project.org/web/packages/simmr/vignettes/simmr.html) and run the commands up to:
```
simmr_out_combine = combine_sources(simmr_out,
                                     to_combine=c('U.lactuca','Enteromorpha'),
                                     new_source_name='U.lac+Ent')
```

You can just keep combining, e.g.:
```
simmr_out_combine_2 = combine_sources(simmr_out_combine,
                                    to_combine=c('Zostera','U.lac+Ent'),
                                    new_source_name='Zos+U.lac+Ent')
```

Hope that helps,

Andrew

**Comment by kabrantes** [comment]
Thanks for the quick answer!! But  I meant two separate pairs. Like seagrass+epiphytes (high d13C), and also mangrove and saltmarsh succulents (low d13C).
Cheers!

**Comment by andrewcparnell** [comment]
You can combine any sources you like in any combination you like, but at each step of calling `combine_sources` you can only combine two sources at a time. If you want a model with sources, e.g. A+B vs C+D you just need run it once to combine A+B and then again to combine C+D. Or am I misunderstanding what you're trying to do?

**Comment by kabrantes** [comment]
Oh yes! Got it! Sorry, I should have got it from your first answer, makes perfect sense, thanks!! :)
