### ISSUE TITLE
Group names

### ISSUE THREAD

**Issue by andrewcparnell** [andrewcparnell/simmr#8]
Request to add in flexibility in groups so they can be character vectors rather than forced to be integers.

**Comment by TonyBicknell** [comment]
Hi Andrew,
Was the ability to change group names implemented? I have been trying to alter the group names when using the compare_groups plot but wasn't having much luck through either changing the input or altering the plot (it might just be me though). I couldn't remove/edit the title for the compare_groups plot either.
Kind regards
Tony

**Comment by andrewcparnell** [comment]
Yes this is implemented in version 0.4.0. See the vignette [here](https://cran.r-project.org/web/packages/simmr/vignettes/simmr.html#running-simmr-on-multiple-groups)
