### ISSUE TITLE
Controlling X-axis ticks in plot(simmr_groups_out,type='boxplot')

### ISSUE THREAD

**Issue by ChrisHarrod** [andrewcparnell/simmr#9]
Dear Andrew

firstly thanks for the nice, fast mixing model.
I have a plotting question, e.g. with this function plot(simmr_groups_out,type='boxplot',group=1,title='simmr output group 1')

I'm probably being really stupid, but is there a quick way to force the boxplots to have a similar format for x axis tick intervals? I have mixing model outputs for 4 groups. For three, the ticks intervals are every 0.25, but for one it's 0.2! obviously, I'd like to get them all in a common format.

Cheers
Chris

**Comment by andrewcparnell** [comment]
Hi Chris,

I'm assuming you're running that command as part of the [simmr vignette](https://cran.r-project.org/web/packages/simmr/vignettes/simmr.html)? And so when you plot group 1, group 2, etc, you want them all to have the same x-axis range?

This isn't currently possible in simmr but I can write you some code which does it?

Andrew

**Comment by ChrisHarrod** [comment]
Hi Andrew
yes - I've blagged the code from the vignette

If you could do that, it would be very, very much appreciated. The manuscript isn't ready yet, but I'd like to look fancy for when we submit it.

Cheers
Chris

**Comment by andrewcparnell** [comment]
Hi Chris,

OK if you run
```
source('https://raw.githubusercontent.com/andrewcparnell/simmr/master/R/plot.simmr_output.R')
plot(simmr_groups_out,type='boxplot',group=1:4, ggargs = ylim(0,1))
```

It should now produce a plot of e.g. each group 1 to 4 each with axis limits going from 0 to 1 (or whatever else you specify).

Andrew

**Comment by ChrisHarrod** [comment]
Hi Andrew
Many thanks for your time
Did this, but got the following error

Error in scale_fill_viridis(discrete = TRUE) :
  could not find function "scale_fill_viridis"

Cheers
Chris

**Comment by andrewcparnell** [comment]
Hi Chris.

Ah. You need some extra package calls before you run the plot command. Likely starting with:
```
library(MASS)
library(compositions)
library(boot)
library(reshape2)
library(coda)
library(viridis)
```
will fix it. 

Andrew

**Comment by ChrisHarrod** [comment]
I suspected as much, but am with crappy Internet. Will install them later tonight.

Many thanks Andrew
Chris


-------- Original message --------

**Comment by andrewcparnell** [comment]
Those packages should all have been installed with simmr, so you shouldn't need to install them again.

Andrew

**Comment by ChrisHarrod** [comment]
Hi Andrew - I finally got back to this and the problem continues...

**Comment by ChrisHarrod** [comment]
Andrew

It’s working now. Not sure what happened, but after a restart, the planets aligned and whammo – it worked ok.

Thanks and apologies for bothering you

C

**Comment by andrewcparnell** [comment]
No worries. Always good to hear a success story. They’re rare enough!

Andrew

------------------------
Prof Andrew Parnell, Hamilton Institute, Maynooth University, Ireland

On 5 Sep 2018, at 21:35, ChrisHarrod <notifications@github.com<mailto:notifications@github.com>> wrote:

Andrew

It’s working now. Not sure what happened, but after a restart, the planets aligned and whammo – it worked ok.

Thanks and apologies for bothering you

C

**Comment by bluepahl** [comment]
Hi Dr. Parnell (and Dr. Harrod)
I've used the code: ggargs = ylim(0,1)) to set the y limits (i.e. the y-axis ticks), however, is there a way to set the xlimits in a similar way? I've tried ggargs=(((ylim(10,20)), (xlim(-19,-13))) but it doesn't like that. I've also tried using ggargs twice, but then it says there's multiple arguments for the ggargs function. 
Thank you for your help,
Blue.

**Comment by andrewcparnell** [comment]
Hi Blue,

Without seeing a reproducible example I'm not sure I can really help you. However, you could try something like:

`plot(simmr_out,type='density') + xlim(0, 0.5)`

...and it might work.

Andrew

**Comment by bluepahl** [comment]
Hi Dr. Parnell, 
Apparently you and Dr. Jackson added xlim and ylim functions into the package to change the axes limits - thank you! 
Second question: Is there a way to assign different colours to the prey groups in the output plots like the boxplots? I'm looking at 11 different predator species and while most of them have the same 5 prey groups, occasionally one with be different and I'd like to be able to assign it a different colour so as not to confuse a reader into thinking the prey items are the same. 
Thank you for your help!
Blue.

**Comment by andrewcparnell** [comment]
Hi Blue,

Yes this is possible but it would require you to learn a little bit of ggplot2 and get inside the `plot.simmr_output` function. In the function you'll see that the fill colour of the boxplots is by source. To change it you'd need create your own variable which represents the colours you want and then colour by this new variable.

I've just put an example of doing this in the [vignette](http://andrewcparnell.github.io/simmr/articles/simmr.html#customising-plots-1) in case you want to change it to your needs. It's currently implemented only in the development version but will soon make it on to the official version.

Andrew

**Comment by ViniciusNeres-Lima** [comment]
> Hi Blue,
> 
> Without seeing a reproducible example I'm not sure I can really help you. However, you could try something like:
> 
> `plot(simmr_out,type='density') + xlim(0, 0.5)`
> 
> ...and it might work.
> 
> Andrew

Hi, Andrew and Blue,

I used 

ggargs= list(ylim(10,20), ylim(-19,-13)) 

and it worked fine.

Vinicius

Andrew, thanks for the simmr.
